### PR TITLE
add redux and dispatch to components

### PR DESCRIPTION
**Pull request by til2to**
In this milestone, these features and requirements were implemented;

- [ ] wrapped the <App> with the <Provider> component from react-redux 
- [ ] passed your configured store into the <Provider>
- [ ] created an initialState variable for your booksSlice.
- [ ] displayed your books, received from the slice, in a reusable component.
- [ ] dispatched actions using useDispatch.
- [ ] added a <Button> component, which includes:
       an event handler that adds a book to the books array (with attributes id, title, and author).
- [ ] added a <Button> component, which includes: 
      an event handler that removes a book from the books array (by id).

### CODE REVIEW

**Review by christianbiring1 — CHANGES_REQUESTED** [review]
Hi @til2to , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 


## Highlights
- [ ] Great work on making the store available in the App through the `Provider` method :+1: 
- [ ] Great work on implementing the deleteBook feature :+1: 

## Required Changes ♻️
- [ ] Kindly make sure the user can be able to add a new book through the input form. As you may notice the user cannot be added right now. Please make sure you fix that.
Hint:
```jsx
import React from "react"
import { useDispatch } from "react-redux"
import { addBook } from "path/to/booksSlice"

function NewBookForm() {
  const [title, setTitle] = useState("")
  const [author, setAuthor] = useState("")
  const books = useSelector((state) => state.books.books)
  const dispatch = useDispatch()

  // Other logic that controls form state

  return (
    <div>
      {/* Rest of form JSX */}
      <Button onClick={() => dispatch(addBook({ title, author }))}>
        Add book
      </Button>
    </div>
  )
}

export default NewBookForm
```
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- make sure your UI looks similar with the original design.
Screenshot from 2023-06-13 16-34-19


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by til2to** [comment]
I will be glad if you can help with these questions.

please have you checked the properties of the book and of the form fields? the author is a drop-down, so from which values should user selects from.

**Comment by christianbiring1** [comment]
> Do you really understand the requirements of this tasks

@til2to YOur dropdown is disabled and once hit the `addbook` button it done not work. you may consider following the hint I just provided above

**Review by Ibizugbe — APPROVED** [review]
Hi @til2to 👋👋,

StandingOvationGIF (8)
 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅

- [x] A user can add a new book using the input form👍.
- [x] Linters are passing👍.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
